name = "CFTransport"
uuid = "aafcb771-6be4-4a54-aeb4-fb9a94868d38"
authors = ["The ClimFlows contributors"]
version = "0.1.3"

[deps]
CFDomains = "3699aaca-035b-4155-96ec-eecb526248de"
ManagedLoops = "36a4119d-6b73-4371-88fe-ba2d91f5495d"
MutatingOrNot = "6a37069a-9a67-4b2d-a34a-f09ab4b23c7c"

[compat]
CFDomains = "0.1.4, 0.2"
ManagedLoops = "0.1.3"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
