name = "CFTransport"
uuid = "aafcb771-6be4-4a54-aeb4-fb9a94868d38"
authors = ["The ClimFlows contributors"]
version = "0.1.0"

[deps]
ManagedLoops = "36a4119d-6b73-4371-88fe-ba2d91f5495d"

[compat]
ManagedLoops = "0.1.3"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
